INFO: 2019-08-06 11:03:53,323: perform_upgrade() 'Last run version was 0.7.2 or earlier, current version is 0.7.2'
INFO: 2019-08-06 11:03:54,670: process_command() 'Received command: []'
INFO: 2019-08-06 11:03:54,672: load_banned() 'Missing or invalid banned URLs list, no URLs will be banned'
INFO: 2019-08-06 11:03:54,757: load() 'Jumble loading'
INFO: 2019-08-06 11:03:54,783: _walk_modules() 'Jumble loading module in __init__ from /usr/share/variety/plugins/__init__.py'
INFO: 2019-08-06 11:03:54,796: _walk_modules() 'Jumble loading module in QuotesDaddySource from /usr/share/variety/plugins/quotes/QuotesDaddySource.py'
INFO: 2019-08-06 11:03:54,798: load() 'Jumble found plugin class: <class 'QuotesDaddySource.QuotesDaddySource'>: {'name': 'QuotesDaddy', 'description': "Fetches quotes from QuotesDaddy's daily quotes RSS feed.\nDoes not support searching by tags or authors.", 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-08-06 11:03:54,799: _walk_modules() 'Jumble loading module in QuotationsPageSource from /usr/share/variety/plugins/quotes/QuotationsPageSource.py'
INFO: 2019-08-06 11:03:54,888: load() 'Jumble found plugin class: <class 'QuotationsPageSource.QuotationsPageSource'>: {'name': 'TheQuotationsPage.com', 'description': 'Fetches quotes from TheQuotationsPage.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-08-06 11:03:54,888: _walk_modules() 'Jumble loading module in __init__ from /usr/share/variety/plugins/quotes/__init__.py'
INFO: 2019-08-06 11:03:54,904: _walk_modules() 'Jumble loading module in GoodreadsSource from /usr/share/variety/plugins/quotes/GoodreadsSource.py'
INFO: 2019-08-06 11:03:54,905: load() 'Jumble found plugin class: <class 'GoodreadsSource.GoodreadsSource'>: {'name': 'Goodreads', 'description': 'Fetches quotes from Goodreads.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-08-06 11:03:54,906: _walk_modules() 'Jumble loading module in LocalFilesSource from /usr/share/variety/plugins/quotes/LocalFilesSource.py'
INFO: 2019-08-06 11:03:54,906: load() 'Jumble found plugin class: <class 'LocalFilesSource.LocalFilesSource'>: {'name': 'Local text files', 'description': 'Displays quotes, defined in local text files.\nPut your own txt files in: ~/.config/variety/pluginconfig/quotes/.\nThe file format is:\n\nquote -- author\n.\nsecond quote -- another author\n.\netc...\n\nExample: http://rvelthuis.de/zips/quotes.txt', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-08-06 11:03:54,951: log_options() 'Loaded options:'
INFO: 2019-08-06 11:03:54,951: log_options() 'change_enabled = False'
INFO: 2019-08-06 11:03:54,951: log_options() 'change_interval = 300'
INFO: 2019-08-06 11:03:54,951: log_options() 'change_on_start = False'
INFO: 2019-08-06 11:03:54,952: log_options() 'clipboard_enabled = False'
INFO: 2019-08-06 11:03:54,952: log_options() 'clipboard_hosts = ['wallhaven.cc', 'wallpapers.net', 'flickr.com', 'imgur.com', 'deviantart.com', 'interfacelift.com', 'vladstudio.com', 'imageshack.us', 'deviantart.net', 'imageshack.com']'
INFO: 2019-08-06 11:03:54,952: log_options() 'clipboard_use_whitelist = True'
INFO: 2019-08-06 11:03:54,952: log_options() 'clock_date_font = Ubuntu Condensed, 30'
INFO: 2019-08-06 11:03:54,952: log_options() 'clock_enabled = False'
INFO: 2019-08-06 11:03:54,952: log_options() 'clock_filter = -density 100 -font `fc-match -f '%{file[0]}' '%CLOCK_FONT_NAME'` -pointsize %CLOCK_FONT_SIZE -gravity SouthEast -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+108] '%H:%M' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+110] '%H:%M' -font `fc-match -f '%{file[0]}' '%DATE_FONT_NAME'` -pointsize %DATE_FONT_SIZE -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %B %d' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %B %d''
INFO: 2019-08-06 11:03:54,952: log_options() 'clock_font = Ubuntu Condensed, 70'
INFO: 2019-08-06 11:03:54,952: log_options() 'configfile = /home/alex/.config/variety/variety.conf'
INFO: 2019-08-06 11:03:54,952: log_options() 'copyto_enabled = False'
INFO: 2019-08-06 11:03:54,952: log_options() 'copyto_folder = Default'
INFO: 2019-08-06 11:03:54,952: log_options() 'desired_color = [160, 160, 160]'
INFO: 2019-08-06 11:03:54,952: log_options() 'desired_color_enabled = False'
INFO: 2019-08-06 11:03:54,952: log_options() 'download_enabled = False'
INFO: 2019-08-06 11:03:54,952: log_options() 'download_folder = /home/alex/.config/variety/Downloaded'
INFO: 2019-08-06 11:03:54,952: log_options() 'download_interval = 600'
INFO: 2019-08-06 11:03:54,952: log_options() 'favorites_folder = /home/alex/.config/variety/Favorites'
INFO: 2019-08-06 11:03:54,952: log_options() 'favorites_operations = [['Downloaded', 'Copy'], ['Fetched', 'Move'], ['Others', 'Copy']]'
INFO: 2019-08-06 11:03:54,952: log_options() 'fetched_folder = /home/alex/.config/variety/Fetched'
INFO: 2019-08-06 11:03:54,952: log_options() 'filters = [[False, 'Keep original', ''], [False, 'Grayscale', '-type Grayscale'], [False, 'Heavy blur', '-blur 120x40'], [False, 'Soft blur', '-blur 20x7'], [False, 'Oil painting', '-paint 8'], [False, 'Pencil sketch', '-colorspace gray \\( +clone -tile ~/.config/variety/pencil_tile.png -draw "color 0,0 reset" +clone +swap -compose color_dodge -composite \\) -fx \'u*.2+v*.8\''], [False, 'Pointilism', '-spread 10 -noise 3'], [False, 'Pixellate', '-scale 3% -scale 3333%']]'
INFO: 2019-08-06 11:03:54,952: log_options() 'icon = Light'
INFO: 2019-08-06 11:03:54,952: log_options() 'lightness_enabled = False'
INFO: 2019-08-06 11:03:54,952: log_options() 'lightness_mode = 0'
INFO: 2019-08-06 11:03:54,952: log_options() 'min_rating = 4'
INFO: 2019-08-06 11:03:54,952: log_options() 'min_rating_enabled = False'
INFO: 2019-08-06 11:03:54,952: log_options() 'min_size = 80'
INFO: 2019-08-06 11:03:54,952: log_options() 'min_size_enabled = False'
INFO: 2019-08-06 11:03:54,952: log_options() 'quota_enabled = True'
INFO: 2019-08-06 11:03:54,953: log_options() 'quota_size = 500'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_authors = '
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_bg_color = [80, 80, 80]'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_bg_opacity = 55'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_change_enabled = False'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_change_interval = 300'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_disabled_sources = ['QuotesDaddy']'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_enabled = False'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_favorites_file = /home/alex/.config/variety/favorite_quotes.txt'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_font = Bitstream Charter 30'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_hpos = 100'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_tags = '
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_text_color = [255, 255, 255]'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_text_shadow = False'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_vpos = 40'
INFO: 2019-08-06 11:03:54,953: log_options() 'quotes_width = 70'
INFO: 2019-08-06 11:03:54,953: log_options() 'safe_mode = False'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_custom_enabled = False'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_custom_folder = /home/alex/Pictures'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_downloads_enabled = False'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_fade = 0.4'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_favorites_enabled = True'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_mode = Fullscreen'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_monitor = All'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_pan = 0.05'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_seconds = 6.0'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_sort_order = Random'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_sources_enabled = True'
INFO: 2019-08-06 11:03:54,953: log_options() 'slideshow_zoom = 0.2'
INFO: 2019-08-06 11:03:54,953: log_options() 'smart_enabled = False'
INFO: 2019-08-06 11:03:54,954: log_options() 'smart_notice_shown = False'
INFO: 2019-08-06 11:03:54,954: log_options() 'smart_register_shown = False'
INFO: 2019-08-06 11:03:54,954: log_options() 'sources = [[False, 3, 'The Favorites folder'], [False, 4, 'The Fetched folder'], [False, 2, '/usr/share/backgrounds'], [False, 6, 'Random wallpapers from Desktoppr.co'], [False, 15, 'Bing Photo of the Day'], [False, 16, 'High-resolution photos from Unsplash.com'], [False, 8, "NASA's Astronomy Picture of the Day"], [False, 11, 'World Sunlight Map - live wallpaper from Die.net'], [False, 7, 'user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'], [True, 2, '/home/alex/Pictures/wallpaper'], [False, 1, '/home/alex/Pictures/wallpaper/H6YM808.jpg']]'
INFO: 2019-08-06 11:03:54,954: log_options() 'stats_enabled = True'
INFO: 2019-08-06 11:03:54,954: log_options() 'stats_notice_shown = False'
INFO: 2019-08-06 11:03:54,954: log_options() 'sync_enabled = True'
INFO: 2019-08-06 11:03:54,954: log_options() 'use_landscape_enabled = True'
INFO: 2019-08-06 11:03:54,954: reload_config() 'No need to clear prepared queue'
INFO: 2019-08-06 11:03:54,954: load_last_change_time() 'Change interval < 6 hours, ignore persisted last_change_time, wait initially the whole interval: 300'
INFO: 2019-08-06 11:03:54,954: update_indicator() 'Setting file info to: /home/alex/Pictures/wallpaper/H6YM808.jpg'
INFO: 2019-08-06 11:03:55,052: regular_change_thread() 'regular_change thread running'
INFO: 2019-08-06 11:03:55,052: regular_change_thread() 'regular_change: waiting till user resumes'
INFO: 2019-08-06 11:03:55,052: prepare_thread() 'Prepare thread running'
INFO: 2019-08-06 11:03:55,052: prepare_thread() 'Prepared buffer contains 0 images'
INFO: 2019-08-06 11:03:55,052: prepare_thread() 'Preparing some images'
INFO: 2019-08-06 11:03:55,054: update_indicator_icon() 'Creating indicator'
INFO: 2019-08-06 11:03:55,056: do_set_wp() 'Calling do_set_wp with /home/alex/Pictures/wallpaper/H6YM808.jpg, time: 1565060635.0563502'
INFO: 2019-08-06 11:03:55,133: update_indicator() 'Setting file info to: /home/alex/Pictures/wallpaper/H6YM808.jpg'
WARNING: 2019-08-06 11:03:55,159: create_menu() 'Variety Slideshow is not installed. This is an optional extension adding pan-and-zoom slideshows to Variety: see https://github.com/peterlevi/variety-slideshow for details'
INFO: 2019-08-06 11:03:55,161: create_indicator() 'indicator backend: fallback tray'
INFO: 2019-08-06 11:03:55,338: set_from_theme_icon() 'Showing status icon variety-indicator from GTK theme'
INFO: 2019-08-06 11:03:55,476: update_indicator() 'Setting file info to: /home/alex/Pictures/wallpaper/H6YM808.jpg'
INFO: 2019-08-06 11:03:55,899: prepare_thread() 'After search prepared buffer contains 9 images'
INFO: 2019-08-06 11:03:58,515: reload() 'Reloading preferences dialog'
INFO: 2019-08-06 11:04:15,071: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-08-06 11:04:21,546: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f9878cef588>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9878cef588>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9878cef588>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-08-06 11:04:51,580: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-08-06 11:04:57,936: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f9878d3d0f0>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9878d3d0f0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9878d3d0f0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-08-06 11:05:27,968: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-08-06 11:05:33,881: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 307, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='tiny.cc', port=80): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Read timed out. (read timeout=5)
INFO: 2019-08-06 11:06:03,913: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-08-06 11:06:10,247: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f9878d286a0>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9878d286a0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9878d286a0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-08-06 11:06:40,278: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-08-06 11:06:46,967: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f9878d9deb8>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9878d9deb8>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9878d9deb8>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
